[package]
name = "starknet_api"
version = "0.1.0"
edition = "2021"

[features]
testing = []

[dependencies]
const_format = { version = "0.2.30" }
const-str = { version = "0.5.3" }
hex = { version = "0.4.3" }
hex-literal = { version = "0.3.4" }
indexmap = { version = "1.9.2", features = ["serde"] }
serde = { version = "1.0.130", features = ["derive", "rc"] }
serde_json = { version = "1.0.81" }
starknet-crypto = { version = "0.2.0" }
thiserror = { version = "1.0.31" }
web3 = { version = "0.18.0" }
derive_more = {version = "0.99.17"}

[dev-dependencies]
assert_matches = { version = "1.5.0" }
