[package]
name = "starknet_api"
version = "0.1.0"
edition = "2021"

[features]
testing = []

[dependencies]
cairo-lang-starknet = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
hex = "0.4.3"
indexmap = { version = "1.9.2", features = ["serde"] }
once_cell = "1.17.1"
serde = { version = "1.0.130", features = ["derive", "rc"] }
serde_json = "1.0.81"
starknet-crypto = "0.2.0"
thiserror = "1.0.31"
web3 = "0.18.0"
derive_more = "0.99.17"

[dev-dependencies]
assert_matches = "1.5.0"
